### PR TITLE
🐛 Fix missing dep in cli package

### LINKED ISSUE #635: packages/cli uses `@oclif/command` but does not declare in it's dependencies
## The problem

looks like it's being used here:
https://github.com/percy/cli/blob/master/packages/cli/index.js#L69

seems that it's relying on package hoisting which causes issues with yarn v3

## Environment

- yarn v3.1.1

## Debug logs

```
Error: @percy/cli tried to access @oclif/command, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @oclif/command (via "@oclif/command/flush")
Required by: @percy/cli@npm:1.0.0-beta.70 (via ~/dev/csi.lk/.yarn/cache/@percy-cli-npm-1.0.0-beta.70-47d784f1db-64b983337f.zip/node_modules/@percy/cli/bin/)
```

## Code to reproduce issue

Create new repo using yarn v3
Install percy cli
Run percy cli
See issue

Edit: looks like `@oclif/errors` is missing too

### PR DESCRIPTION
**Pull request by csi-lk**
resolves #635

### CODE REVIEW

**Comment by Robdel12** [comment]
Hey @csi-lk! Thanks for the PR -- we're about to PR a big refactor that removes oclif and also adds support for both pnpm & yarn 2+. I'll leave this open until that PR opens (and then close this one out)

**Comment by csi-lk** [comment]
@Robdel12 excellent, I did find myself needing to workaround a few pieces to get it to work with yarn 2

I'll watch this PR for updates to the new version, cheers

**Comment by csi-lk** [comment]
Shall we close this @Robdel12 ? 😅

**Comment by wwilsman** [comment]
This should be fixed with #670, but a future PR will add full yarn 2+ compatibility 😃

**Pull request closed without merging**
